redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - tosca-redis:/var/lib/redis/data

tosca:
  build: .
  command: bin/rails server
  links:
    - redis
#  volumes:
#    - .:/tosca
  ports:
    - '8000:8000'
      

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  env_file:
    .toscanini.env
  links:
    - redis
#  volumes:
#    - .:/tosca
