redis:
  image: redis
  command: redis-server --appendonly yes --syslog-enabled yes

postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=tosca"
    - "POSTGRES_PASSWORD=tosca"
  ports:
    - "5432:5432"

tosca:
  build: .
  command: bin/rails server -b 0.0.0.0
  links:
    - redis
    - postgres
  ports:
    - "3000:3000"
  volumes:
    - .:/tosca

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  env_file:
    .toscanini.env
  links:
    - redis
    - postgres
  volumes:
    - .:/tosca
