redis:
  image: redis
  command: redis-server --appendonly yes

tosca:
  build: .
  command: bin/rails server -b 0.0.0.0
  links:
    - redis
  ports:
    - '3000:3000'
  volumes:
    - .:/tosca


sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  env_file:
    .toscanini.env
  links:
    - redis
  volumes:
    - .:/tosca
